" A (not so) minimal vimrc.

" Use system clipboard
set clipboard=unnamedplus

" Map leader key to space
let mapleader=" "


" Enable line numbers
set number

" Enable syntax highlighting
syntax enable

" Enable filetype detection
filetype plugin indent on


" Set tab width to 4 spaces
set tabstop=4
set shiftwidth=4
set expandtab

" ctrl-shift-x is cut
vnoremap <C-S-X> "+x

" ctrl-shift-c is copy
vnoremap <C-S-C> "+y

" ctrl-shift-v is paste
map <C-S-V> "+gP
imap <C-S-V>  <C-R>+
cmap <C-S-V>  <C-R>+

" Map Leader + a to select all
nnoremap <leader>a ggVG

" Map Leader + w to close the current tab
nnoremap <leader>w :tabclose<CR>

" Map Leader + ] to indent the current line or selected lines
nnoremap <leader>] >>
vnoremap <leader>] >gv

" Map Leader + [ to de-indent the current line or selected lines
nnoremap <leader>[ <<
vnoremap <leader>[ <gv

" Map Ctrl + z to undo
nnoremap <C-z> u
inoremap <C-z> <C-o>u

" Map Ctrl + r to redo (default behavior)
nnoremap <C-r> <C-r>
inoremap <C-r> <C-o><C-r>
